### ISSUE TITLE
Find and list information on new patient forms for medical, dental and vision providers

### ISSUE THREAD

**Issue by varadk** [cornell-tech-webmd/product-studio#1]

**Comment by recursion915** [comment]
**Information in common among medical/dental/vision care:**
Name:
Nickname:
DOB:
SSN:
Health Insurance:Primary and Secondary:
Address:
Phone #:
Allergies:
Emergency Contact/Nearest Friend/Relative:

**Medical Care**
Consent Status:
DNA Status:
List of all surgeries and date:
List of all serious medical illnesses:
List all major behavioral and psychiatric diagnoses:
Women's Health: Pregnant; Age menstruation started/stopped
Men's Health: Date of Last Prostate Exam
Special Needs:

**Dental Care**
Lots of details checkbox including resporatory and cardionvascular (several examples are listed below):
Chronic face/jaw pain
Clicking/popping jaw
Difficulty opening/closing jaw
Unable to chew food
Sores on lips
Unpleasant taste/bad breath
Burning tongue/lip
Swelling mouth
Loose teeth

**Vision**
Purpose of coming to vision care: 
Last Eye Exam:
Glasses or not:
Contact lens:
Eye problems:
Name of family doctor:

[dental care.pdf](https://github.com/cornell-tech-webmd/product-studio/files/480476/dental.care.pdf)
[Eye Form.pdf](https://github.com/cornell-tech-webmd/product-studio/files/480477/Eye.Form.pdf)
[medical care.pdf](https://github.com/cornell-tech-webmd/product-studio/files/480475/medical.care.pdf)
